# Generated by Django 5.1.1 on 2024-09-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='Название')),
                ('author', models.CharField(max_length=250, null=True, verbose_name='Автор')),
                ('image', models.ImageField(null=True, upload_to='book/', verbose_name='Вид')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Scince', 'Scince')], max_length=50, null=True, verbose_name='Жанр')),
            ],
        ),
    ]
