# Generated by Django 5.1.1 on 2024-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybook',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Science', 'Science')], max_length=50, null=True, verbose_name='Жанр'),
        ),
    ]
